core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')), # EL NAMESPACE ES EL NOMBRE DE APP_NAME EEN STORE.URLS
    path('store/basket/', include('store_basket.urls', namespace='basket')), # EL NAMESPACE ES EL NOMBRE DE APP_NAME EEN STORE_BASKET.URLS
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.products_allActive, name='all_products'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
]

store_basket/urls.py
from django.urls import path
from . import views

app_name = 'store_basket'


urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True) # Nombre de la categoría
    slug = models.SlugField(max_length=255, unique=True) # parte de la dirección URL

    class Meta:
        verbose_name_plural = 'Categories' # para que django no ponga nombre "categorys"

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug]) # STORE(NOMBRE DE LA APP):PRODUCT_DETAIL(NOMBRE DEL PATH), LE PASAMOS EL SLUG

    def __str__(self):
        return self.name
        

class ProductManager(models.Manager): # CUSTOM MANAGER PARA QUERYSETS DE PRODUCTOS SOLO ACTIVOS
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE) # no puede haber productos sin categoría
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager() # DEFAULT MANAGER PARA HACER QUERYS
    products = ProductManager() # CUSTOM MANAGER DEFINIDO PARA QUERYS DE LOS PRODUCTOS SOLO ACTIVOS

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)# ORDENA EN LA BASE DE DATOS POR EL MOMENTO EN EL QUE FUE CREADO EL PRODUCTO

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug]) # STORE(NOMBRE DE LA APP):PRODUCT_DETAIL(NOMBRE DEL PATH), LE PASAMOS EL SLUG
    
    def __str__(self):
        return self.title
    
    

store_basket/models.py
from django.db import models

# Create your models here.

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

def index(self):
    pass


def products_allActive(request):
    products = Product.products.all() # query de la base de datos para obtener todos los productos
    context = {
        'products': products
    }
    return render(request, 'store/home.html', context) # STORE/HOME.HTML EN REALIDAD ES TEMPLATES/STORE/HTML, PERO LA PRIMER PARTE ESTÁ ACLARADA EN SETTINGS

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True) # SI EL PRODUCTO ESTÁ EN STOCK, LO MUESTRA. ASGINA A SLUG EL SLUG RECUPERADO EN LAS URL
    context = {
        'product': product
    }
    return render(request, 'store/products/detail.html', context)

def category_list(request, category_slug): # devuelve los productos de una sola categoria al template
    category = get_object_or_404(Category, slug=category_slug) #RECUPERA EL SLUG DE LA CATEGORIA Y LA GUARDA EN SLUG
    products = Product.products.filter(category=category) # QUERY DE LA CATEGORIA ELEGIDA
    context = { # VARIABLES PARA USAR EN LOS TEMPLATES
        'category': category, # CATEGORIA
        'products': products # PRODUCTOS DEL QUERY DE LA CATEGORIA
    }
    return render(request, 'store/products/category.html', context) # DEVUELVE AL TEMPLATE

store_basket/views.py
from django.shortcuts import render
from django. shortcuts import get_object_or_404

from django.http import JsonResponse

from .basket import Basket
from store.models import Product

def basket_summary(request):
    return render(request, 'store/basket/summary.html')

def basket_add(request): #COLLECT DATA QUE NOS ENVIO JQUERY DESDE ADD BASKET
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid')) # RECUPERA EL PRODUCT ID DEL SCRIPT DE JS EN EL TEMPLATE (id=productid)
        product_qty = int(request.POST.get('productqty')) # RECUPERA EL PRODUCTQTY DEL SCRIPT DE JS EN EL TEMPLATE (id=productqty)
        product = get_object_or_404(Product, id=product_id) # retrieves the product data from the database
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({ # LA VARIABLE RESPONSE ES UN ARCHIVO JSON PARA QUE PUEDA UTILIZARLO EL NAVEGADOR EN EL JS
            'qty': basketqty
        })

        return response # devuelve el archivo JSON

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</head>

  <body>
    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
            <div class="container-fluid">
                <a class="navbar-brand" href="/store">Inicio</a>
                <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
                <!--BUTTON BAR-->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="#">Nuevos productos!</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Categorias</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        <li><a class="dropdown-item" href="/store">Todas</a></li>
                        {% for c in categories %}
                        <li><a class="dropdown-item" href="{{c.get_absolute_url}}">{{c.name|title}}</a></li>
                        {% endfor %}
                    </ul>
                    </li>
                </ul>
                <!-- SEARCH BAR -->
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                    <span style="width: 50px"></span>
                </form>
                <!-- STORE_BASKET -->
                <a type "button" role="button" href="{% url "store_basket:basket_summary" %}" class="btn btn-outline-secondary"> <!-- store_basket(VA A LA APP_NAME BASKET):basket_summary(VA AL PATH CON NAMESPACE BASKET_SUMMARY)-->
                  
                  {% with total_qty=basket|length %}
                      <div id="basket-qty" class="d-inline-flex">
                          {% if total_qty > 0 %}
                              {{ total_qty }}
                          {% else %}
                              0
                          {% endif %}
                      </div>
                  {% endwith %} 
                  
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cart-check-fill" viewBox="0 0 16 16">
                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-1.646-7.646l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708.708z"/>
                  </svg>
                  Carrito
                </a>
                </div>
            </div>
        </nav>
    </header>

    <div id="content">{% block content %} {%endblock%}</div>
  </body>
</html>

templates/store/basket/summary.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
Basket Summary
{% endblock %}
{% block content %}
Basket page
{% endblock %}

templates/store/home.html
{% extends "./base.html" %} {%load static%} {% block title %} Home {% endblock%} 
{% block content %}
<div class="bg-dark text-secondary px-4 py-5 text-center">
  <div class="py-5">
    <h1 class="display-5 fw-bold text-white">Tienda en linea</h1>
    <div class="col-lg-6 mx-auto">
      <p class="fs-5 mb-4">
        Bienvenido a mi primer tienda ecommerce! 
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <button
          type="button"
          class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold"
        >
          Custom button
        </button>
        <button type="button" class="btn btn-outline-light btn-lg px-4">
          Secondary
        </button>
      </div>
    </div>
  </div>
</div>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for p in products %}
      <div class="col">
        <div class="card shadow-sm">
          <a href="{{p.get_absolute_url}}" ><img class="img-fluid" alt="Responsive image" src="{{p.image.url}}"></a>

          <div class="card-body">
            <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{p.get_absolute_url}}">{{p.title|title}}</a>
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-sm btn-outline-secondary">
                  Añadir al carrito
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  Ver detalles
                </button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/store/products/category.html
{% extends "../base.html" %} {%load static%} {% block title %} Home {% endblock%} 
{% block content %}
<div class="bg-dark text-secondary px-4 py-5 text-center">
  <div class="py-5">
    <h1 class="display-5 fw-bold text-white">Tienda en linea</h1>
    <div class="col-lg-6 mx-auto">
      <p class="fs-5 mb-4">
        Bienvenido a mi primer tienda en linea!
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <button
          type="button"
          class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold"
        >
          Custom button
        </button>
        <button type="button" class="btn btn-outline-light btn-lg px-4">
          Secondary
        </button>
      </div>
    </div>
  </div>
</div>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for p in products %}
      <div class="col">
        <div class="card shadow-sm">
          <a href="{{p.get_absolute_url}}" ><img class="img-fluid" alt="Responsive image" src="{{p.image.url}}"></a>

          <div class="card-body">
            <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{p.get_absolute_url}}">{{p.title|title}}</a>
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" id="add-button" class="btn btn-sm btn-outline-secondary">
                  Añadir al carrito
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  Ver detalles
                </button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/store/products/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="album py-5 bg-light">
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Cantidad</label>
                                <select id="select" class="h6" style="width:50px;height:40px;">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
                                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Añadir al carrito</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "store_basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}